name = "momgagym-nutrition"
pages_build_output_dir = "dist"

[ai]
binding = "AI"

[[d1_databases]]
binding = "NUTRITION_DB"
database_name = "nutrition-cms-db"
database_id = "37fe650f-60d0-4c2c-84d0-53d989837fd4"
