export const OFFICIAL_NUTRITION_SOURCES = [
  { brand: '스타벅스', aliases: ['스타벅스', 'starbucks'], category: '커피/음료', url: 'https://www.starbucks.co.kr/menu/drink_list.do' },
  { brand: '투썸플레이스', aliases: ['투썸', 'twosome'], category: '커피/음료', url: 'https://www.twosome.co.kr' },
  { brand: '메가MGC커피', aliases: ['메가커피', '메가mgc', 'mega'], category: '커피/음료', url: 'https://www.mega-mgccoffee.com' },
  { brand: '컴포즈커피', aliases: ['컴포즈', 'compose'], category: '커피/음료', url: 'https://composecoffee.com' },
  { brand: '이디야커피', aliases: ['이디야', 'ediya'], category: '커피/음료', url: 'https://www.ediya.com' },
  { brand: '더벤티', aliases: ['더벤티', 'theventi'], category: '커피/음료', url: 'https://www.theventi.co.kr' },
  { brand: '공차', aliases: ['공차', 'gongcha'], category: '커피/음료', url: 'https://www.gong-cha.co.kr' },
  { brand: '스무디킹', aliases: ['스무디킹', 'smoothieking'], category: '커피/음료', url: 'https://www.smoothieking.co.kr' },
  { brand: '파리바게뜨', aliases: ['파리바게뜨', '파리바게트', 'paris baguette'], category: '베이커리/디저트', url: 'https://www.paris.co.kr' },
  { brand: '배스킨라빈스', aliases: ['배스킨', '베스킨', 'baskin'], category: '베이커리/디저트', url: 'https://www.baskinrobbins.co.kr' },
  { brand: '맥도날드', aliases: ['맥도날드', '맥날', 'mcdonald'], category: '패스트푸드/버거', url: 'https://www.mcdonalds.co.kr' },
  { brand: '버거킹', aliases: ['버거킹', 'burgerking'], category: '패스트푸드/버거', url: 'https://www.burgerking.co.kr' },
  { brand: '롯데리아', aliases: ['롯데리아', 'lotteria'], category: '패스트푸드/버거', url: 'https://www.lotteria.com' },
  { brand: '맘스터치', aliases: ['맘스터치', 'momstouch'], category: '패스트푸드/버거', url: 'https://momstouch.co.kr' },
  { brand: '써브웨이', aliases: ['써브웨이', '서브웨이', 'subway'], category: '패스트푸드/샌드위치', url: 'https://www.subway.co.kr/menuList/sandwich' },
  { brand: 'KFC', aliases: ['kfc', '케이에프씨'], category: '패스트푸드/치킨', url: 'https://www.kfckorea.com' },
  { brand: '본죽', aliases: ['본죽', 'bonif'], category: '한식/죽', url: 'https://www.bonif.co.kr/menu/list?brdCd=BF101' },
  { brand: '한솥', aliases: ['한솥', 'hansot'], category: '한식/도시락', url: 'https://www.hansot.co.kr/menu/menu_list' },
  { brand: '신전떡볶이', aliases: ['신전', '신전떡볶이'], category: '분식', url: 'http://sinjeon.co.kr/menu/menu1.php' },
  { brand: '김가네', aliases: ['김가네', 'gimgane'], category: '분식/김밥', url: 'http://gimgane.co.kr/menu/menu1' },
  { brand: '아웃백', aliases: ['아웃백', 'outback'], category: '패밀리 레스토랑', url: 'https://www.outback.co.kr/menu/menuList.do?menuIdx=45' },
  { brand: 'VIPS', aliases: ['vips', '빕스'], category: '패밀리 레스토랑', url: 'https://www.ivips.co.kr:444/menu/menuList.asp' },
  { brand: '애슐리퀸즈', aliases: ['애슐리', 'ashley'], category: '패밀리 레스토랑', url: 'https://www.myashley.co.kr/Menu/AshleyMenu/Menu01.aspx' },
  { brand: '매드포갈릭', aliases: ['매드포갈릭', 'madforgarlic'], category: '패밀리 레스토랑', url: 'https://www.madforgarlic.com/menu' },
];

export const OFFICIAL_BRAND_FOODS = [
  {
    brand: '스타벅스',
    keys: ['스타벅스아메리카노', '스타벅스카페아메리카노', '카페아메리카노', '아메리카노tall'],
    serving: 'Tall 1잔',
    sourceLabel: '스타벅스 공식 영양정보',
    sourceUrl: 'https://www.starbucks.co.kr/menu/drink_list.do',
    emoji: '커피',
    calories: 10,
    carb: 2,
    protein: 1,
    fat: 0,
    saturatedFat: 0,
    sodium: 5,
    sugar: 0,
    fiber: 0,
    leucine: 0,
  },
  {
    brand: '스타벅스',
    keys: ['스타벅스라떼', '스타벅스카페라떼', '카페라떼', '라떼tall'],
    serving: 'Tall 1잔',
    sourceLabel: '스타벅스 공식 영양정보',
    sourceUrl: 'https://www.starbucks.co.kr/menu/drink_list.do',
    emoji: '커피',
    calories: 110,
    carb: 10,
    protein: 6,
    fat: 5,
    saturatedFat: 4.6,
    sodium: 70,
    sugar: 8,
    fiber: 0,
    leucine: 420,
  },
  {
    brand: '맥도날드',
    keys: ['맥도날드빅맥', '빅맥', 'bigmac'],
    serving: '버거 1개',
    sourceLabel: '맥도날드 공식 메뉴/영양정보',
    sourceUrl: 'https://www.mcdonalds.co.kr',
    emoji: '버거',
    calories: 583,
    carb: 47,
    protein: 27,
    fat: 32,
    saturatedFat: 11,
    sodium: 902,
    sugar: 8,
    fiber: 3,
    leucine: 2100,
  },
  {
    brand: '버거킹',
    keys: ['버거킹와퍼', '와퍼', 'whopper'],
    serving: '버거 1개',
    sourceLabel: '버거킹 공식 메뉴/영양정보',
    sourceUrl: 'https://www.burgerking.co.kr',
    emoji: '버거',
    calories: 619,
    carb: 48,
    protein: 29,
    fat: 34,
    saturatedFat: 12,
    sodium: 809,
    sugar: 10,
    fiber: 3,
    leucine: 2300,
  },
  {
    brand: '써브웨이',
    keys: ['써브웨이이탈리안비엠티', '서브웨이이탈리안비엠티', '이탈리안비엠티', 'italianbmt'],
    serving: '15cm 샌드위치 1개',
    sourceLabel: '써브웨이 공식 메뉴정보',
    sourceUrl: 'https://www.subway.co.kr/menuList/sandwich',
    emoji: '샌드위치',
    calories: 388,
    carb: 46,
    protein: 21,
    fat: 16,
    saturatedFat: 5,
    sodium: 1064,
    sugar: 8,
    fiber: 4,
    leucine: 1600,
  },
  {
    brand: '써브웨이',
    keys: ['써브웨이로스트치킨', '서브웨이로스트치킨', '로스트치킨', 'roastedchicken'],
    serving: '15cm 샌드위치 1개',
    sourceLabel: '써브웨이 공식 메뉴정보',
    sourceUrl: 'https://www.subway.co.kr/menuList/sandwich',
    emoji: '샌드위치',
    calories: 300,
    carb: 47,
    protein: 26,
    fat: 5,
    saturatedFat: 1.5,
    sodium: 605,
    sugar: 8,
    fiber: 4,
    leucine: 2100,
  },
];

export function findOfficialBrandFood(name) {
  const normalized = normalizeKeyword(name);
  return OFFICIAL_BRAND_FOODS.find((entry) => entry.keys.some((key) => normalized.includes(normalizeKeyword(key))));
}

export function findOfficialNutritionSources(name) {
  const normalized = normalizeKeyword(name);
  return OFFICIAL_NUTRITION_SOURCES.filter((entry) =>
    entry.aliases.some((alias) => normalized.includes(normalizeKeyword(alias))),
  );
}

function normalizeKeyword(value) {
  return String(value || '').toLowerCase().replace(/[\s™®.&·ㆍ_-]/g, '');
}
