import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const { chromium } = await import(process.env.MEAL_PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.env.MEAL_CHROME_PATH ? { executablePath: process.env.MEAL_CHROME_PATH } : {}) });
await mkdir('.qa', { recursive: true });
const errors = [];
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, serviceWorkers: 'block' });
await context.addInitScript(() => { window.TextDetector = class { async detect() { return []; } }; });
let visionStatus = 200;
const foods = [
  { name: '샐러드', confidence: .75, estimatedGrams: 160, position: { x: .3, y: .35 } },
  { name: '계란', confidence: .75, estimatedGrams: 50, quantity: 1, unitLabel: '개', position: { x: .73, y: .32 } },
  { name: '흰쌀밥', confidence: .75, estimatedGrams: 210, position: { x: .55, y: .76 } },
];
await context.route('**/api/**', async (route) => {
  const url = route.request().url();
  await route.fulfill({ status: url.includes('vision-analyze') ? visionStatus : 200, json: url.includes('vision-analyze') ? { ok: visionStatus === 200, provider: 'qa-fixture', foods: visionStatus === 200 ? foods : [] } : { ok: true, candidates: [], images: [] } });
});
const fixture = await context.newPage();
await fixture.setViewportSize({ width: 520, height: 440 });
await fixture.setContent('<body style="margin:0"><svg width="520" height="440" viewBox="0 0 520 440" xmlns="http://www.w3.org/2000/svg"><rect width="520" height="440" fill="#d9cebd"/><circle cx="260" cy="230" r="197" fill="#f5f0e6" stroke="#c9c2b8" stroke-width="6"/><g fill="#639351"><ellipse cx="135" cy="150" rx="60" ry="35" transform="rotate(-25 135 150)"/><ellipse cx="190" cy="170" rx="60" ry="35" transform="rotate(30 190 170)"/><ellipse cx="160" cy="110" rx="55" ry="30"/></g><g fill="#d06443"><circle cx="145" cy="142" r="18"/><circle cx="195" cy="133" r="17"/></g><ellipse cx="380" cy="147" rx="63" ry="82" fill="#fff9e6" transform="rotate(25 380 147)"/><ellipse cx="380" cy="157" rx="36" ry="43" fill="#edbd48"/><ellipse cx="273" cy="335" rx="95" ry="55" fill="#d4cbbe"/><ellipse cx="273" cy="315" rx="89" ry="54" fill="#fffdf2"/></svg>');
const image = await fixture.screenshot();
await fixture.close();
await writeFile('.qa/meal-fixture.png', image);
const page = await context.newPage();
page.on('pageerror', (error) => errors.push(error.message));
page.setDefaultTimeout(15000);
const saved = () => page.evaluate(() => JSON.parse(localStorage.getItem('nutritionReports.v1') || '[]'));
async function screenshot(name) { await page.screenshot({ path: '.qa/' + name + '.png', fullPage: false }); }
async function noOverflow() { assert.equal(await page.locator('.meal-screen').last().evaluate((element) => element.scrollWidth <= element.clientWidth + 1), true, 'screen must fit viewport'); }
try {
  await page.goto('http://127.0.0.1:5173');
  await page.getByLabel('음식 사진 고르기').setInputFiles({ name: 'meal.png', mimeType: 'image/png', buffer: image });
  await page.getByRole('heading', { name: '음식과 양이 맞나요?' }).waitFor();
  assert.equal(await page.locator('.food-photo-tag.is-placed').count(), 3);
  await noOverflow();
  await screenshot('review-mobile');
  const second = page.locator('.review-food-card').nth(1);
  assert.equal(await page.getByRole('button', { name: '맞아요 · 결과 보기 →' }).isDisabled(), true);
  await page.locator('.review-food-card').nth(0).getByRole('button', { name: '이만큼', exact: true }).click();
  await second.getByRole('button', { name: '반 개', exact: true }).click();
  await page.locator('.review-food-card').nth(2).getByRole('button', { name: '1공기', exact: true }).click();
  await page.getByRole('button', { name: '맞아요 · 결과 보기 →' }).click();
  await page.getByRole('heading', { name: '오늘 먹은 한 끼' }).waitFor();
  assert.equal(await page.locator('.food-result-card').count(), 3);
  await page.getByLabel('언제 먹었나요?').selectOption('간식·기타');
  await page.getByLabel('이 식사 시간이 맞아요').check();
  await noOverflow();
  await page.locator('.meal-screen').evaluate((element) => element.scrollTop = 0);
  await screenshot('result-mobile');
  await page.locator('.meal-total-card').scrollIntoViewIfNeeded();
  await screenshot('nutrition-mobile');
  // Check 320px text layout, and keyboard-focusable labels leading to food cards.
  await page.setViewportSize({ width: 320, height: 740 });
  await noOverflow();
  await page.locator('.food-photo-tag').first().click();
  assert.equal(await page.locator('.food-result-card').first().evaluate((element) => document.activeElement === element), true);
  await screenshot('food-mobile-320');
  await page.setViewportSize({ width: 390, height: 844 });
  const firstCard = page.locator('.food-result-card').first();
  await firstCard.getByText('양을 숫자로 입력하기', { exact: true }).click();
  const weight = firstCard.locator('.meal-portion').getByLabel('먹은 양 (g)', { exact: true });
  await weight.fill('0');
  assert.equal(await page.getByRole('button', { name: '✓ 이 식사 저장하기' }).isDisabled(), true);
  await weight.fill('80');
  await firstCard.getByLabel('저울로 잰 무게예요').check();
  await weight.fill('60');
  assert.equal(await firstCard.getByLabel('저울로 잰 무게예요').isChecked(), false);
  await firstCard.getByLabel('저울로 잰 무게예요').check();
  await firstCard.getByText('계산 근거 보기', { exact: true }).click();
  await firstCard.evaluate((element) => element.scrollIntoView({ behavior: 'instant', block: 'start' }));
  await screenshot('food-evidence-mobile');
  assert.equal(await page.getByText(/신뢰도 높음|자동 신뢰 \d+%/).count(), 0);
  await page.getByRole('button', { name: '✓ 이 식사 저장하기' }).click();
  await page.getByRole('heading', { name: '나의 식사 기록' }).waitFor();
  let entries = await saved();
  assert.equal(entries.length, 1);
  assert.equal(entries[0].mealType, '간식·기타');
  assert.equal(entries[0].items[1].consumedAmount, 25);
  assert.ok(entries[0].items.every((item) => item.position && item.nameConfirmed && item.portionConfirmed));
  assert.equal(entries[0].items[1].portionSource, 'household');
  assert.equal(entries[0].items[0].portionSource, 'measured');
  assert.ok(entries[0].imageUrl.startsWith('data:image/jpeg'));
  const original = entries[0];
  await screenshot('diary-mobile');
  await page.locator('.diary-meal-card').scrollIntoViewIfNeeded();
  await screenshot('record-card-mobile');
  await page.getByRole('button', { name: '이름·양 고치기' }).click();
  const form = page.locator('.diary-meal-card form');
  await form.getByLabel(/섭취량/).first().fill(String(original.items[0].consumedAmount / 2));
  await form.getByRole('button', { name: '수정 저장' }).click();
  await page.getByText('수정한 내용을 저장했어요.', { exact: true }).waitFor();
  entries = await saved();
  assert.ok(Math.abs(entries[0].items[0].nutrients.protein - original.items[0].nutrients.protein / 2) < .02);
  assert.ok(entries[0].totals.calories < original.totals.calories);
  assert.equal(entries[0].macroPercent.carb + entries[0].macroPercent.protein + entries[0].macroPercent.fat, 100);
  assert.ok(entries[0].originalAnalysis);
  await page.getByRole('button', { name: '7일', exact: true }).click();
  await noOverflow();
  await screenshot('weekly-mobile');
  await page.getByRole('button', { name: '30일', exact: true }).click();
  await noOverflow();
  await page.getByRole('button', { name: '오늘', exact: true }).click();
  page.once('dialog', (dialog) => dialog.accept());
  await page.getByRole('button', { name: '지우기', exact: true }).click();
  await page.getByRole('heading', { name: '오늘의 첫 식사를 남겨볼까요?' }).waitFor();
  assert.equal((await saved()).length, 0);
  await page.getByRole('button', { name: '되돌리기', exact: true }).click();
  await page.getByText('기록을 다시 넣었어요.', { exact: true }).waitFor();
  assert.equal((await saved()).length, 1);
  await page.reload();
  await page.getByRole('button', { name: '오늘 기록 열기' }).click();
  await page.locator('.diary-meal-card').first().waitFor();
  assert.equal(await page.locator('.diary-meal-card').count(), 1);
  await page.setViewportSize({ width: 1280, height: 900 });
  await noOverflow();
  await screenshot('diary-desktop');
  await page.evaluate(() => localStorage.setItem('nutritionCameraProfile.v2', JSON.stringify({ mode: 'child', age: 10, height: 140, weight: 35, gender: '남성', medical: ['없음'], sport: '없음' })));
  await page.reload();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: '오늘 기록 열기' }).click();
  await page.getByText('골고루 먹고, 튼튼하게 자라요', { exact: true }).waitFor();
  assert.equal(await page.getByText(/하루 참고 목표/).count(), 0);
  await screenshot('child-diary-mobile');
  await page.getByRole('button', { name: '← 사진 찍기', exact: true }).click();
  visionStatus = 503;
  await page.getByLabel('음식 사진 고르기').setInputFiles({ name: 'meal.png', mimeType: 'image/png', buffer: image });
  await page.getByRole('button', { name: '기다리지 않고 이름 입력하기' }).click();
  await page.getByLabel('먹은 음식 이름').fill('계란');
  await page.getByRole('button', { name: '찾기', exact: true }).click();
  await page.getByRole('button', { name: '맞아요 · 결과 보기 →' }).waitFor({ state: 'visible' });
  await page.getByRole('button', { name: '1개', exact: true }).click();
  await page.getByRole('button', { name: '맞아요 · 결과 보기 →' }).click();
  await page.getByRole('heading', { name: '오늘 먹은 한 끼' }).waitFor();
  await page.getByText('포장지 영양정보 입력하기', { exact: true }).click();
  await page.getByLabel('이 식사 시간이 맞아요').check();
  const labelForm = page.locator('details.meal-card').filter({ has: page.getByText('포장지 영양정보 입력하기', { exact: true }) });
  await labelForm.getByLabel('식품명', { exact: true }).fill('검사용 포장 음료');
  await labelForm.getByLabel('포장지 숫자의 기준 분량', { exact: true }).fill('250mL');
  await labelForm.getByLabel(/^열량/).fill('200');
  await labelForm.getByLabel(/^탄수화물/).fill('30');
  await labelForm.getByLabel(/^단백질/).fill('10');
  await labelForm.getByLabel(/^지방/).fill('4');
  const labelCard = page.locator('.food-result-card').last();
  assert.equal(await page.getByRole('button', { name: '✓ 이 식사 저장하기' }).isDisabled(), true);
  await labelCard.getByRole('button', { name: '반 회분', exact: true }).click();
  await labelCard.getByLabel('제품 이름·표시 분량·아래 숫자가 포장지와 같아요').check();
  assert.equal(await labelCard.getByRole('button', { name: '반 회분', exact: true }).getAttribute('aria-pressed'), 'true');
  await labelCard.evaluate((element) => element.scrollIntoView({ behavior: 'instant', block: 'start' }));
  await screenshot('label-portion-mobile');
  await page.getByRole('button', { name: '✓ 이 식사 저장하기' }).click();
  await page.getByRole('heading', { name: '나의 식사 기록' }).waitFor();
  assert.equal((await saved()).length, 2);
  const savedLabel = (await saved())[0].items.find((item) => item.foodName === '검사용 포장 음료');
  assert.equal(savedLabel.nutrients.calories, 100);
  assert.equal(savedLabel.nutrients.protein, 5);
  assert.equal(savedLabel.portionSource, 'label-serving');
  assert.deepEqual(errors, []);
  console.log('PASS: photo → review → portion → result → save; 320/390/1280px; macros; history correction; delete/restore; reload; 7/30 days; child mode; AI failure/manual fallback.');
} catch (error) {
  await screenshot('failure');
  await writeFile('.qa/failure-page.txt', await page.locator('body').innerText());
  throw error;
} finally { await browser.close(); }
